name: build on multi runner

on:
  push:
  workflow_dispatch:


env:
  REGISTRY_IMAGE: pkking/app

concurrency:
  group: multi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-x64:
    runs-on: ubuntu-22.04
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/pkking
          username: pkking
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.REGISTRY_IMAGE }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          echo "DIGEST=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  build-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/pkking
          username: pkking
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.REGISTRY_IMAGE }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          echo "DIGEST=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  merge:
    runs-on: ubuntu-latest
    needs:
      - build-x64
      - build-arm64
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/pkking
          username: pkking
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Create manifest list and push
        run: |
          docker manifest create ${{ env.REGISTRY_IMAGE }} -a ${{ env.REGISTRY_IMAGE }}@sha256:${{ needs.build-x64.outputs.DIGEST }} -a ${{ env.REGISTRY_IMAGE }}@sha256:${{ needs.build-arm64.outputs.DIGEST }}
          docker manifest push ${{ env.REGISTRY_IMAGE }}
      
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}